# Generated by Django 3.1.13 on 2021-10-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
